//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteInspeccion.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IServicioArchivos")]
    public interface IServicioArchivos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArchivos/ObtenerArchivos", ReplyAction="http://tempuri.org/IServicioArchivos/ObtenerArchivosResponse")]
        string[] ObtenerArchivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArchivos/ObtenerArchivos", ReplyAction="http://tempuri.org/IServicioArchivos/ObtenerArchivosResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerArchivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArchivos/BorrarArchivo", ReplyAction="http://tempuri.org/IServicioArchivos/BorrarArchivoResponse")]
        void BorrarArchivo(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArchivos/BorrarArchivo", ReplyAction="http://tempuri.org/IServicioArchivos/BorrarArchivoResponse")]
        System.Threading.Tasks.Task BorrarArchivoAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArchivos/DoWork", ReplyAction="http://tempuri.org/IServicioArchivos/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArchivos/DoWork", ReplyAction="http://tempuri.org/IServicioArchivos/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioArchivosChannel : ClienteInspeccion.ServiceReference2.IServicioArchivos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioArchivosClient : System.ServiceModel.ClientBase<ClienteInspeccion.ServiceReference2.IServicioArchivos>, ClienteInspeccion.ServiceReference2.IServicioArchivos {
        
        public ServicioArchivosClient() {
        }
        
        public ServicioArchivosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioArchivosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioArchivosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioArchivosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ObtenerArchivos() {
            return base.Channel.ObtenerArchivos();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerArchivosAsync() {
            return base.Channel.ObtenerArchivosAsync();
        }
        
        public void BorrarArchivo(string path) {
            base.Channel.BorrarArchivo(path);
        }
        
        public System.Threading.Tasks.Task BorrarArchivoAsync(string path) {
            return base.Channel.BorrarArchivoAsync(path);
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
